"""Core module for Simply-MCP framework.

This module contains the core functionality including:
- Type definitions
- Configuration management
- Error handling
"""

from simply_mcp.core.config import (
    AuthConfigModel,
    FeatureFlagsModel,
    LogConfigModel,
    RateLimitConfigModel,
    ServerMetadataModel,
    SimplyMCPConfig,
    TransportConfigModel,
    get_default_config,
    load_config,
    load_config_from_env,
    load_config_from_file,
    validate_config,
)
from simply_mcp.core.errors import (
    AuthenticationError,
    AuthorizationError,
    ConfigFileNotFoundError,
    ConfigFormatError,
    ConfigValidationError,
    ConfigurationError,
    ConnectionError,
    HandlerError,
    HandlerExecutionError,
    HandlerNotFoundError,
    InvalidHandlerSignatureError,
    MessageError,
    RateLimitExceededError,
    RequiredFieldError,
    SchemaValidationError,
    SecurityError,
    SimplyMCPError,
    TransportError,
    TransportNotSupportedError,
    TypeValidationError,
    ValidationError,
)
from simply_mcp.core.types import (
    APIStyle,
    APIStyleInfo,
    AuthConfig,
    AuthType,
    FeatureFlags,
    HandlerContext,
    HandlerFunction,
    JSONDict,
    JSONValue,
    LogConfig,
    LogFormat,
    LogLevel,
    ProgressReporter,
    ProgressUpdate,
    PromptConfig,
    RateLimitConfig,
    RequestContext,
    ResourceConfig,
    ServerConfig,
    ServerMetadata,
    ToolConfig,
    TransportConfig,
    TransportType,
    ValidationError as ValidationErrorType,
    ValidationResult,
)

__all__ = [
    # Config
    "AuthConfigModel",
    "FeatureFlagsModel",
    "LogConfigModel",
    "RateLimitConfigModel",
    "ServerMetadataModel",
    "SimplyMCPConfig",
    "TransportConfigModel",
    "get_default_config",
    "load_config",
    "load_config_from_env",
    "load_config_from_file",
    "validate_config",
    # Errors - Base
    "SimplyMCPError",
    # Errors - Configuration
    "ConfigurationError",
    "ConfigFileNotFoundError",
    "ConfigValidationError",
    "ConfigFormatError",
    # Errors - Transport
    "TransportError",
    "ConnectionError",
    "TransportNotSupportedError",
    "MessageError",
    # Errors - Handlers
    "HandlerError",
    "HandlerNotFoundError",
    "HandlerExecutionError",
    "InvalidHandlerSignatureError",
    # Errors - Validation
    "ValidationError",
    "SchemaValidationError",
    "TypeValidationError",
    "RequiredFieldError",
    # Errors - Security
    "SecurityError",
    "AuthenticationError",
    "AuthorizationError",
    "RateLimitExceededError",
    # Types
    "APIStyle",
    "APIStyleInfo",
    "AuthConfig",
    "AuthType",
    "FeatureFlags",
    "HandlerContext",
    "HandlerFunction",
    "JSONDict",
    "JSONValue",
    "LogConfig",
    "LogFormat",
    "LogLevel",
    "ProgressReporter",
    "ProgressUpdate",
    "PromptConfig",
    "RateLimitConfig",
    "RequestContext",
    "ResourceConfig",
    "ServerConfig",
    "ServerMetadata",
    "ToolConfig",
    "TransportConfig",
    "TransportType",
    "ValidationErrorType",
    "ValidationResult",
]
